In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv',usecols=['name',"seller_type",'transmission','owner','fuel'])
df

,name,fuel,seller_type,transmission,owner
0,Maruti 800 AC,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,Diesel,Individual,Manual,First Owner


# Label and Ordinal Encoder in Sklearn 

# To summarize
Ordinal Variables --> OrdinalEncoder : Owner, Seller_type, Transmission Target or label variables --> LabelEncoder: fuel

In [3]:
df.drop('name',axis=1,inplace=True)

In [4]:
df

,fuel,seller_type,transmission,owner
0,Petrol,Individual,Manual,First Owner
1,Petrol,Individual,Manual,First Owner
2,Diesel,Individual,Manual,First Owner
3,Petrol,Individual,Manual,First Owner
4,Diesel,Individual,Manual,Second Owner
...,...,...,...,...
4335,Diesel,Individual,Manual,Second Owner
4336,Diesel,Individual,Manual,Second Owner
4337,Petrol,Individual,Manual,Second Owner
4338,Diesel,Individual,Manual,First Owner


# For show me the actual how many types of variables available in that category 

In [5]:
df['transmission'].value_counts ()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

In [6]:
#  str.strip() in pandas (and Python in general) means:

# Remove any leading and trailing whitespace (like spaces, tabs, or newlines) from a string.

df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv',usecols=['name',"seller_type",'transmission','owner','fuel'])
df['transmission'] = df['transmission'].map({ 'Manual':0,'Automatic':1 })

In [7]:
df.drop('name',axis=1,inplace=True)

In [8]:
df

,fuel,seller_type,transmission,owner
0,Petrol,Individual,0,First Owner
1,Petrol,Individual,0,First Owner
2,Diesel,Individual,0,First Owner
3,Petrol,Individual,0,First Owner
4,Diesel,Individual,0,Second Owner
...,...,...,...,...
4335,Diesel,Individual,0,Second Owner
4336,Diesel,Individual,0,Second Owner
4337,Petrol,Individual,0,Second Owner
4338,Diesel,Individual,0,First Owner


In [9]:
df['seller_type'].value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [10]:
df['seller_type'] = df['seller_type'].map({'Individual':0,'Dealer':1,'Trustmark Dealer':2})

In [11]:
df.sample(15) #	•	df.sample(n) → returns n random rows.

,fuel,seller_type,transmission,owner
1962,Diesel,0,0,Second Owner
3554,Diesel,0,0,First Owner
743,Petrol,1,0,First Owner
4290,Petrol,0,0,Second Owner
2389,Petrol,1,0,Second Owner
2699,Diesel,0,0,First Owner
2826,Diesel,0,0,First Owner
3561,Diesel,0,0,First Owner
189,Petrol,0,0,First Owner
1349,Petrol,0,0,Second Owner


In [12]:
df.head(15)

,fuel,seller_type,transmission,owner
0,Petrol,0,0,First Owner
1,Petrol,0,0,First Owner
2,Diesel,0,0,First Owner
3,Petrol,0,0,First Owner
4,Diesel,0,0,Second Owner
5,Petrol,0,0,First Owner
6,Petrol,0,0,First Owner
7,Petrol,0,0,Second Owner
8,Petrol,0,0,First Owner
9,CNG,0,0,First Owner


In [13]:
df.tail(15)

,fuel,seller_type,transmission,owner
4325,Petrol,0,0,Second Owner
4326,Petrol,0,0,Third Owner
4327,Petrol,0,0,Second Owner
4328,Diesel,0,0,Second Owner
4329,Petrol,0,0,Second Owner
4330,Diesel,0,0,Second Owner
4331,Diesel,0,0,Third Owner
4332,Diesel,0,0,First Owner
4333,Diesel,0,0,Second Owner
4334,Diesel,0,0,First Owner


In [14]:
df['owner'].value_counts()

owner
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = df.drop('fuel',axis=1)
y=df['fuel']

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42 )

In [18]:
X_train

,seller_type,transmission,owner
227,0,0,First Owner
964,0,0,First Owner
2045,0,0,Second Owner
1025,0,0,First Owner
4242,1,0,First Owner
...,...,...,...
3444,0,0,First Owner
466,0,0,First Owner
3092,1,0,First Owner
3772,0,0,First Owner


In [19]:
y_train

227     Diesel
964     Diesel
2045    Petrol
1025    Diesel
4242    Diesel
         ...  
3444    Diesel
466     Diesel
3092    Diesel
3772    Diesel
860     Petrol
Name: fuel, Length: 3472, dtype: object

# Applying Label Encoder

In [20]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [21]:
le = LabelEncoder() # Predicted Variable ko jisko me predict karna chata hu uspe only Label Encoder use hota hai 


In [22]:
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.fit_transform(y_test)

In [23]:
df['fuel'].value_counts()

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [24]:
y_train_scaled 

array([1, 1, 4, ..., 1, 1, 4], shape=(3472,))

In [25]:
X_train

,seller_type,transmission,owner
227,0,0,First Owner
964,0,0,First Owner
2045,0,0,Second Owner
1025,0,0,First Owner
4242,1,0,First Owner
...,...,...,...
3444,0,0,First Owner
466,0,0,First Owner
3092,1,0,First Owner
3772,0,0,First Owner


In [26]:
# Ordinal encoder use karunga tabhi jab first owner is greater than second owner and third owner is greater that second owner 

# Baki seller_type and transmission pe bhi ordinal encoder use kar sakta hu ...

oe = OrdinalEncoder()
X_train_transform = oe.fit_transform(X_train)
X_test_transform = oe.fit_transform(X_test)

In [27]:
X_train_transform

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 2.],
       ...,
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], shape=(3472, 3))

In [28]:
X_test_transform

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 2.],
       ...,
       [0., 0., 2.],
       [2., 0., 0.],
       [1., 0., 0.]], shape=(868, 3))