<a href="https://colab.research.google.com/github/A-ghori/sklearn/blob/main/Numpy_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ndarray + dimensions
shape, ndim, size, dtype
Indexing & slicing
Boolean masking
Fancy indexing
reshape, flatten, ravel
transpose
concatenate, stack
Broadcasting ⭐
Aggregations: sum, mean, std, min, max
axis properly samajhna ⭐
Missing/invalid numerical values
Random numbers / sampling
Vectorization**

2D array

In [ ]:
import numpy as np

x = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(f" : this mean all rows 1 mean only 1st col ", x[:, 1])
print(f"only last row",x[-1])
print(f"Only last col ", x[:, -1])
print(f"last col second row", x[1,2])

 : this mean all rows 1 mean only 1st col  [20 50 80]
only last row [70 80 90]
Only last col  [30 60 90]
last col second row 60


In [ ]:
#np.sum(x, axis=1) #[10+20+30] = 60     [40,50,60] = 150  [70,80,90] = 240] # row wise sum use axis = 1
np.sum (x, axis=0) # [[10,40,70] = 120  [20,50,80] = 150  [30,60,90] = 180] # column wise sum use axis = 0


array([120, 150, 180])

3d Array


In [ ]:
y = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(y.shape)
np.sum(y, axis=0) # axis 0  means first dimmension ko collapse karo 1+7 = 8, 2+8 = 10, 3+9 = 12 , 4+10=14, 5+11=16, 6+12=18
np.sum(y, axis=1) # axis 1  means second dim ko collapse karo 1+4 = 5 , 2+5 = 7
np.sum(y,axis=2) # rows sum
y.mean(axis=0)

(2, 2, 3)


array([[4., 5., 6.],
       [7., 8., 9.]])

***Reshape Flatten Ravel Squeeze / expand_dims***

In [ ]:
x = np.array([1,2,3,4,5,6])
x.shape
x.reshape(2,3)
x.reshape(-1,2) # same as x.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

Flatten

In [ ]:
x = np.array([
    [1,2,3],
    [4,5,6]
])
print(x.flatten())
# Important Flatten copy banata hai
y = x.flatten()
y[0] = 100 # y ke copy me just change huya value orginal values same hai
print(y)
print(x.flatten())

[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [ ]:
y = x.ravel()
print(y) # flatten -> always copy
         # ravel -> possible view
# both working is same but difference big data set me atahai

[1 2 3 4 5 6]


In [ ]:
x = np.array([
    [
        1,
        2,
        3
    ]
])
x.squeeze().shape # (3,)
x.squeeze()

array([1, 2, 3])

In [ ]:
X = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
#print(X[:, -1])
#print(X[0:2])
print(X[1:2])
print(X[1,2])
print(X[0:3, 1:3])

[[40 50 60]]
60
[[20 30]
 [50 60]
 [80 90]]


Boolean Masking

In [ ]:
X = np.array([10,25,40,55,70])
print(X[X > 40])
print(X[X<=25])

# Multiple Conditions
age = np.array([18,12,32,11,21,100,40,60,77,50])
print(age[(age >= 20) & (age <= 40)])

[55 70]
[10 25]
[32 21 40]


In [ ]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

#1. 50 Find
print(X[1,1])
#2 [70, 80, 90]
print(X[2:3])
#3. [30, 60, 90]
print(X[:,-1])
#4. [[20,30], [50,60]]
print(X[0:2, 1:3])
#5. All values > 50
print(X[ X > 50])
#6. All values between 30 and 80
print(X[(X >= 30) & (X <= 80)])



50
[[70 80 90]]
[30 60 90]
[[20 30]
 [50 60]]
[60 70 80 90]
[30 40 50 60 70 80]


**Broadcasting**

In [ ]:
import numpy as np

X = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

X + 10

array([[20, 30, 40],
       [50, 60, 70]])

In [ ]:
X = np.array([
    [10,20,30],
    [40,50,60]
])
bias = np.array([1,2,3])
X + bias

array([[11, 22, 33],
       [41, 52, 63]])

In [ ]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300]
])

mean = X.mean(axis=0)
print(mean)
X - mean


[ 20. 200.]


array([[ -10., -100.],
       [   0.,    0.],
       [  10.,  100.]])

In [ ]:
x = np.array([
    [10,20,30],
    [50,60,70],
    [80,90,100]
])

print(x.sum(axis=1))

[ 60 180 270]
