# Installation

In [1]:
pip install scikit-learn



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


# Sklearn BuiltIn Dataset Import 

In [2]:
from sklearn import datasets

In [3]:
breast = datasets.load_breast_cancer
breast ()

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,

In [4]:
X,y = datasets.load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Train Test Split

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

In [8]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner


# Store the selling price in Y axis and drop from the X axis 

In [9]:
X = df.drop('selling_price',axis=1)
y = df['selling_price']

In [10]:
X


,name,year,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner


In [11]:
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...  
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [12]:
X.shape
y.shape

(4340,)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
X_train.shape

(3472, 7)

In [15]:
X_test.shape

(868, 7)

In [16]:
import pandas as pd 


# Feature Scaling 

In [17]:
df = df[['selling_price','km_driven', 'year']]

In [18]:
df

,selling_price,km_driven,year
0,60000,70000,2007
1,135000,50000,2007
2,600000,100000,2012
3,250000,46000,2017
4,450000,141000,2014
...,...,...,...
4335,409999,80000,2014
4336,409999,80000,2014
4337,110000,83000,2009
4338,865000,90000,2016


# Applying Normalization : Minmax Scalling

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler = MinMaxScaler()

In [21]:
scaler_df = scaler.fit_transform(df)  # We use fit transform to convert columns all the datas into MinMax
scaler_df

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]], shape=(4340, 3))

In [22]:
scale_df = pd.DataFrame(data=scaler_df, columns=df.columns)
scale_df

,selling_price,km_driven,year
0,0.004505,0.086783,0.535714
1,0.012950,0.061988,0.535714
2,0.065315,0.123976,0.714286
3,0.025901,0.057028,0.892857
4,0.048423,0.174807,0.785714
...,...,...,...
4335,0.043919,0.099181,0.785714
4336,0.043919,0.099181,0.785714
4337,0.010135,0.102900,0.607143
4338,0.095158,0.111579,0.857143


# Train Test Split

In [23]:
df

,selling_price,km_driven,year
0,60000,70000,2007
1,135000,50000,2007
2,600000,100000,2012
3,250000,46000,2017
4,450000,141000,2014
...,...,...,...
4335,409999,80000,2014
4336,409999,80000,2014
4337,110000,83000,2009
4338,865000,90000,2016


In [24]:
from sklearn.model_selection import train_test_split



In [25]:
X = df.drop("selling_price", axis=1)
y = df["selling_price"]

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
X_train

,km_driven,year
227,20000,2017
964,50000,2018
2045,25000,2013
1025,70000,2011
4242,72000,2017
...,...,...
3444,50000,2006
466,80000,2011
3092,51000,2016
3772,80000,2013


In [28]:
X_test

,km_driven,year
3978,80000,2010
1448,27000,2019
2664,41723,2008
17,141000,2014
1634,60000,2016
...,...,...
3468,60000,2007
3164,120000,2015
416,40000,2011
1616,6480,2017


In [29]:
y_test

3978    165000
1448    250000
2664    120000
17      450000
1634    730000
         ...  
3468    130000
3164    350000
416     150000
1616    650000
2480    575000
Name: selling_price, Length: 868, dtype: int64

# Feauture-Scalling: Normalization: MinMax Scaler

In [30]:
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.fit_transform(X_test)

In [31]:
X_train_scaler
X_test_scaler

array([[0.22636103, 0.58333333],
       [0.07449857, 0.95833333],
       [0.11668481, 0.5       ],
       ...,
       [0.11174785, 0.625     ],
       [0.01570201, 0.875     ],
       [0.08309456, 0.95833333]], shape=(868, 2))

In [32]:
X_train_scale = pd.DataFrame(data=X_train_scaler,columns=X_train.columns)
X_test_scale = pd.DataFrame(data=X_test_scaler, columns=X_test.columns)
X_test_scale

,km_driven,year
0,0.226361,0.583333
1,0.074499,0.958333
2,0.116685,0.500000
3,0.401146,0.750000
4,0.169054,0.833333
...,...,...
863,0.169054,0.458333
864,0.340974,0.791667
865,0.111748,0.625000
866,0.015702,0.875000


In [33]:
X_train_scale

,km_driven,year
0,0.024794,0.892857
1,0.061988,0.928571
2,0.030993,0.750000
3,0.086783,0.678571
4,0.089263,0.892857
...,...,...
3467,0.061988,0.500000
3468,0.099181,0.678571
3469,0.063227,0.857143
3470,0.099181,0.750000


In [34]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [35]:
df1 = pd.read_csv("Social_Network_Ads.csv")
df1

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [36]:
df1.drop('User ID',axis=1,inplace=True)

In [37]:
df1

,Gender,Age,EstimatedSalary,Purchased
0,Male,19,19000,0
1,Male,35,20000,0
2,Female,26,43000,0
3,Female,27,57000,0
4,Male,19,76000,0
...,...,...,...,...
395,Female,46,41000,1
396,Male,51,23000,1
397,Female,50,20000,1
398,Male,36,33000,0


# I want to transform male and female strings into numbers 


In [38]:
df1['Gender'] = df['Gender'].map({'Male':1,'Female':0})
df1

KeyError: 'Gender'

# Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop("EstimatedSalary", axis=1)
y = "EstimatedSalary"

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train

,User ID,Gender,Age,Purchased
3,15603246,Female,27,0
18,15704583,Male,46,1
202,15735549,Female,39,1
250,15810075,Female,44,0
274,15692819,Female,57,1
...,...,...,...,...
71,15726358,Female,24,0
106,15706185,Female,26,0
270,15680752,Female,43,0
348,15579212,Male,39,0


In [ ]:
print(type(y))

<class 'str'>


In [ ]:
y = df["EstimatedSalary"]

In [ ]:
print(y.shape)

(400,)


In [ ]:
y

0      19000
1      20000
2      43000
3      57000
4      76000
       ...  
395    41000
396    23000
397    20000
398    33000
399    36000
Name: EstimatedSalary, Length: 400, dtype: int64

# Applying StandardScaler

In [ ]:
print(X_train.dtypes)

User ID       int64
Gender       object
Age           int64
Purchased     int64
dtype: object


In [ ]:
X_train["Gender"] = X_train["Gender"].map({"Male": 0, "Female": 1})
X_test["Gender"] = X_test["Gender"].map({"Male": 0, "Female": 1})

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [ ]:
X_train

,km_driven,year
227,20000,2017
964,50000,2018
2045,25000,2013
1025,70000,2011
4242,72000,2017
...,...,...
3444,50000,2006
466,80000,2011
3092,51000,2016
3772,80000,2013


In [ ]:
np.round(X_train.describe(),2)

,km_driven,year
count,3472.00,3472.00
mean,66014.13,2013.12
std,46905.39,4.21
min,1.00,1992.00
25%,35000.00,2011.00
50%,60000.00,2014.00
75%,90000.00,2016.00
max,806599.00,2020.00
